version: '3.9'

services:
  ubuntu:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /home/qa/code
    volumes:
      - ".:/home/qa/code"
    entrypoint: ["sh", "-c", "sleep infinity"]
    env_file:
      - .env
    environment:
      - TZ=Asia/Tokyo
      - LC_ALL=en_US.UTF-8
