# https://docs.docker.com/reference/compose-file/
# BUILDKIT_PROGRESS=plain docker compose build
version: '3.9'

services:
  ubuntu-qa:
    build:
      context: .
      dockerfile: ./ubuntu/Dockerfile.qa
    working_dir: /home/qa/code
    volumes:
      - ".:/home/qa/code"
    entrypoint: ["sh", "-c", "sleep infinity"]
    env_file:
      - .env
    environment:
      - TZ=Asia/Tokyo
      - LC_ALL=en_US.UTF-8
  
  ubuntu-latest:
    build:
      context: .
      dockerfile: ./ubuntu/Dockerfile.latest
    working_dir: /home/ubuntu/code
    volumes:
      - ".:/home/ubuntu/code"
    entrypoint: ["sh", "-c", "sleep infinity"]
    environment:
      - TZ=Asia/Tokyo
      - LC_ALL=en_US.UTF-8

  ubuntu-noble:
    build:
      context: .
      dockerfile: ./ubuntu/Dockerfile.noble
    working_dir: /home/ubuntu/code
    volumes:
      - ".:/home/ubuntu/code"
    entrypoint: ["sh", "-c", "sleep infinity"]
    environment:
      - TZ=Asia/Tokyo
      - LC_ALL=en_US.UTF-8

  # init db
  # docker-compose run --rm redash create_db
  # postgres://username:password@host:5432/dbname
  # postgres://me:${SECRET}@postgres:5432/me
  redash:
    image: redash/redash:latest
    command: redash
    depends_on:
      - postgres
      - redis
    ports:
      - "5000:5000"
    environment:
      PYTHONUNBUFFERED: 0
      REDASH_LOG_LEVEL: "INFO"
      REDASH_REDIS_URL: "redis://redis:6379/0"
      REDASH_DATABASE_URL: "postgresql://postgres@postgres/postgres"
      REDASH_COOKIE_SECRET: redash_cookie_secret
      REDASH_WEB_WORKERS: 4
      REDASH_MAIL_SERVER: "smtp2http"
      REDASH_MAIL_DEFAULT_SENDER: "me@lehungio.com"
  
  worker:
    image: redash/redash:latest
    command: scheduler
    environment:
      PYTHONUNBUFFERED: 0
      REDASH_LOG_LEVEL: "INFO"
      REDASH_REDIS_URL: "redis://redis:6379/0"
      REDASH_DATABASE_URL: "postgresql://postgres@postgres/postgres"
      QUEUES: "queries,scheduled_queries,celery"
      WORKERS_COUNT: 2
      REDASH_MAIL_SERVER: "smtp2http"
      REDASH_MAIL_DEFAULT_SENDER: "me@lehungio.com"
  
  redis:
    image: redis:3.0-alpine

  postgres:
    image: postgres:9.5.6-alpine
    ports:
    - "5432:5432"
  
  nginx-redash:
    image: redash/nginx:latest
    ports:
      - "5000:80"
    depends_on:
      - redash
    links:
      - redash:redash