# Use the official Ubuntu base image
FROM ubuntu:latest

# Update package index and install dependencies
RUN apt-get update && \
    apt-get install -y git curl iputils-ping telnet vim unzip

# WORKDIR /home/qa/code
# COPY ./build/$CURRENT_BRANCH/dependencies.sh .
# RUN chmod +x dependencies.sh

# # Verify dependencies
# CMD ["./dependencies.sh"]