# Use the official base image
FROM jenkins/jenkins:latest

# Switch to root user
USER root

# Build extra dependencies for Jenkins Docker official image
WORKDIR /
COPY ./jenkins/dependencies.sh .
RUN chmod +x dependencies.sh

# Insstall dependencies
RUN ./dependencies.sh

# Switch back to the Jenkins user (if required for later stages)
USER jenkins

# Version check
COPY ./jenkins/version.sh .
RUN chmod +x version.sh
CMD ["./version.sh"]