# Latest version update
name: Automation

#  UTC+0 / JST+9
#
# cron time
# 0 (minute)
# 5 (hour)
# * (day of the month)
# * (month)
# 1 (day of the week, where 0 is Sunday and 1 is Monday)
#
# "0 20 * * *" - Run every day at 5:00 am JST
# "0 20 * * *" - Run every week on Monday at 5:00 am JST
on:
  workflow_dispatch:
  schedule: 
    - cron: "0 20 * * 1"

jobs:
  build-ubuntu-qa:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: ubuntu-qa
      run: docker build . --file ./ubuntu/Dockerfile.qa --tag ubuntu-qa:$(date +%s)

  build-ubuntu-latest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: ubuntu-lastest
      run: docker build . --file ./ubuntu/Dockerfile.latest --tag ubuntu-latest:$(date +%s)

  build-ubuntu-noble:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: ubuntu-noble
      run: docker build . --file ./ubuntu/Dockerfile.noble --tag ubuntu-noble:$(date +%s)

  build-php-latest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: php-fpm
      run: docker build . --file ./php/Dockerfile.latest --tag php:$(date +%s)

  build-scala-bionic:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: scala-bionic
      run: docker build . --file ./scala/build/Dockerfile.bionic --tag scala-bionic:$(date +%s)
  build-scala-mantic:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: scala-mantic
      run: docker build . --file ./scala/build/Dockerfile.mantic --tag scala-mantic:$(date +%s)
  build-scala-maintenance:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: scala-maintenance
      run: docker build . --file ./scala/build/Dockerfile.maintenance --tag scala-mantenance:$(date +%s)
  

  build-jenkins-latest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: jenkins-latest
      run: docker build . --file ./jenkins/Dockerfile.latest --tag jenkins-latest:$(date +%s)