name: Coding Test

on:
  push:
    branches: [ "coding*", "scala*" ]

jobs:
  inspect-code:
    name: '[Required] Inspect code'
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          fetch-depth: 2
      - name: Set up Node.js
        uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4.0.3
        with:
          cache: npm
          node-version-file: '.nvmrc'
      - name: Install dependencies
        run: npm ci
        env:
          TEST: true
      - name: Check code
        run: ls -all
  
  # TEST
  test-scala-coding:  
    runs-on: ubuntu-latest  
    environment: CI
    steps:  
      - uses: actions/checkout@v4  
      - name: Set up Scala and sbt  
        uses: olafurpg/setup-scala@v14  
        with:  
          java-version: adopt@1.11  
      - name: Run tests  
        working-directory: ./scala/coding  
        run: |  
          sbt clean coverage test coverageReport  
      - name: Upload coverage to Codecov  
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN}}
        with:  
          fail_ci_if_error: true