name: Scala Test

on:
  push:
    branches: [ "scala*" ]

jobs:
  # TEST
  test-scala-coding:  
    runs-on: ubuntu-latest  
    environment: CI
    steps:  
      - uses: actions/checkout@v4  
      - name: Set up Scala and sbt  
        uses: olafurpg/setup-scala@v14  
        with:  
          java-version: adopt@1.11  
      - name: Run tests  
        working-directory: ./scala/coding  
        run: |  
          sbt clean coverage test coverageReport  
      - name: Upload coverage to Codecov  
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN}}
        with:  
          fail_ci_if_error: true