name: 'Close stale issues and PRs'
on:
  schedule:
    - cron: '30 1 * * *'
  workflow_dispatch:

# Declare default permissions as read only.
permissions: read-all

jobs:
  stale:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/stale@28ca1036281a5e5922ead5184a1bbf96e5fc984e # v9.0.0
        with:
          # Issue settings
          stale-issue-message: >
            This issue has been automatically locked due to inactivity. Please
            comment if you would like to reopen the issue.
          close-issue-message: >
            This issue has been automatically closed due to inactivity.
          stale-issue-label: 'unconfirmed'
          exempt-issue-labels: 'confirmed,feature'
          # PR settings
          days-before-pr-close: -1